// AUTO-GENERATED by scripts/i18n-build-autotranslate{,-via-aya}.js — DO NOT EDIT.
// Source strings come from scripts/i18n-harvest-pick-sources.js.
// lib/i18n-pick.ts imports this module to localize pick(locale, de, en) calls.

// Generated: 2026-04-25T10:18:33.552Z
// Sources:   4706 unique English strings
// Locales:   1

const autotranslate: Record<string, Record<string, string>> = {
  "sv": {
    " • ": " • ",
    "\"Not a Pentest\" Notice": "„Inte Pentest“-meddelande",
    "# CORRECT — Least-Privilege Role": "# Rätt — Minstprivilegierad rolla",
    "# Default-Deny for all namespaces": "# Standardinställning för alla namnrom: Neja → Nej",
    "# Explicitly allow: Frontend → Backend": "# Tillåt explicit: Frontend → Backend"
  }
}

export default autotranslate
