// AUTO-GENERATED by scripts/i18n-build-autotranslate{,-via-aya}.js — DO NOT EDIT.
// Source strings come from scripts/i18n-harvest-pick-sources.js.
// lib/i18n-pick.ts imports this module to localize pick(locale, de, en) calls.

// Generated: 2026-04-25T16:43:14.330Z
// Sources:   4706 unique English strings
// Locales:   30

const autotranslate: Record<string, Record<string, string>> = {
  "af": {},
  "ar": {},
  "bg": {},
  "bn": {},
  "cs": {},
  "da": {},
  "el": {},
  "es": {},
  "fi": {},
  "fr": {},
  "he": {},
  "hi": {},
  "hu": {},
  "id": {},
  "it": {},
  "ja": {},
  "ko": {},
  "ms": {},
  "nl": {},
  "no": {},
  "pl": {},
  "pt": {},
  "ro": {},
  "ru": {},
  "sv": {},
  "th": {},
  "tr": {},
  "uk": {},
  "vi": {},
  "zh": {}
}

export default autotranslate
